TOPDIR?=..
SUBDIR= apply col colrm column diff diff3 expand false indent jot lam leave lndir \
	logger look lorder mkdep readlink sdiff sed shar split stat unifdef vis \
	which xargs xinstall 

SKIPDIR= awk basename bc biff cal calendar cmp compress comm \
	cut dc dirname du encrypt env file find fmt fold \
	from ftp getconf getent getopt head hexdump id join \
	logname mail file ftp tail tee telnet tftp time touch tr true tsort tty \
	ul units uname unexpand uniq unvis uudecode uuencode vacation wc what mktemp \
 	htpasswd cu newsyslog banner cap_mkdb whois pkg-config pr printenv printf rcs  \
	csplit ctags deroff yes

include ${.TOPDIR}/mk/bsd.subdir.mk
