TOPDIR?=..
SUBDIR= apply basename cal calendar cmp colrm col column comm cut du diff \
	diff3 dirname encrypt env expand false find fmt fold getconf getent \
	getopt grep head hexdump id join jot lam leave lndir logger logname \
	look nice nl nohup paste patch pr printenv printf readlink renice rev \
	rs sdiff sed shar signify sort spell split stat tail tee time touch tr \
	true tsort tty ul uname units unexpand uniq unvis vis wc which xinstall \
	newsyslog banner xargs csplit yes

SKIPDIR= awk bc biff cap_mkdb compress ctags cu dc deroff file from ftp htpasswd \
	 indent lorder mail mkdep mktemp pkg-config rcs telnet tftp unifdef \
	 uudecode uuencode vacation what whois

include ${.TOPDIR}/mk/bsd.subdir.mk
