TOPDIR?=..
SUBDIR=	compress diff3 diff mktemp readlink sdiff shar split stat which

SKIPDIR= apply awk basename bc biff cal calendar cmp colrm col column comm \
	cut dc dirname du encrypt env expand false file find fmt fold \
	from ftp getconf getent getopt grep head hexdump id indent join jot lam leave \
	lndir logger logname look lorder mail mkdep file ftp cu tail tee telnet tftp time touch tr true tsort tty \
	ul units uname unexpand uniq unvis uudecode uuencode vacation vis wc what \
 	xinstall htpasswd cu newsyslog banner cap_mkdb unifdef whois xargs pkg-config pr printenv printf rcs  \
	csplit ctags deroff yes

include ${.TOPDIR}/mk/bsd.subdir.mk
